//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LSWebBroker.rc
//
#define IDR_RT_MANIFEST1                1
#define IDD_IOERRORDLG                  103
#define IDI_SHIP                        126
#define IDI_REDICON                     127
#define IDR_MAINFRAME                   128
#define IDR_LSWebBrokerTYPE             129
#define IDD_SETUP_FOLDER_DLG            132
#define IDB_BACK                        134
#define IDB_CHANGEBTN                   135
#define IDB_EXITBTN                     136
#define IDB_SETUPBTN                    137
#define IDB_XBTN                        138
#define IDB_ERROR_BACK                  140
#define IDB_SOLUTIONBTN                 141
#define IDB_BACK_TW                     142
#define IDB_CHANGEBTN_TW                143
#define IDB_ERROR_BACK_TW               144
#define IDB_EXITBTN_TW                  145
#define IDB_SETUPBTN_TW                 146
#define IDB_SOLUTIONBTN_TW              147
#define IDD_LOGINDLG                    148
#define IDB_LOGIN_BACK                  150
#define IDB_LOGIN_CANCELBTN             151
#define IDB_LOGIN_ENTERBTN              152
#define IDB_LOGIN_ENTRYBTN              153
#define IDB_LOGIN_FINDBTN               154
#define IDB_BITMAP2                     155
#define IDB_LOGIN_IDSAVEBTN             155
#define IDB_LOGIN_EDIT_NORMAL           156
#define IDB_LOGIN_EDIT_PW_NORMAL        157
#define IDB_LOGIN_EDIT_PW_SELECT        158
#define IDB_LOGIN_EDIT_SELECT           159
#define IDB_LOGIN_FINDPW_BTN            160
#define IDB_ERROR_BACK_ID               161
#define IDB_BACK_ID                     162
#define IDB_CHANGEBTN_ID                163
#define IDB_EXITBTN_ID                  164
#define IDB_SETUPBTN_ID                 165
#define IDB_SOLUTIONBTN_ID              166
#define IDB_ERROR_BACK_JP               167
#define IDB_BACK_JP                     168
#define IDB_CHANGEBTN_JP                169
#define IDB_EXITBTN_JP                  170
#define IDB_SETUPBTN_JP                 171
#define IDB_SOLUTIONBTN_JP              172
#define IDB_ERROR_BACK_TH               173
#define IDB_BACK_TH                     174
#define IDB_CHANGEBTN_TH                175
#define IDB_EXITBTN_TH                  176
#define IDB_SETUPBTN_TH                 177
#define IDB_BITMAP1                     178
#define IDB_SOLUTIONBTN_TH              178
#define IDB_LOGIN_CHANNEL               179
#define IDB_CHANNEL_DAUM                181
#define IDB_CHANNEL_MAIN                182
#define IDB_CHANNEL_MGAME               183
#define IDB_CHANNEL_NAVER               184
#define IDB_CHANNEL_NEXON               185
#define IDB_CHANNEL_TOONI               186
#define IDB_BACK_UI                     187
#define IDB_ENTER_UI                    188
#define IDB_FIND_IDPW                   189
#define IDB_LOGIN_EDIT_UI_PW_NORMAL     190
#define IDB_BACK_US                     190
#define IDB_BITMAP4                     191
#define IDB_LOGIN_EDIT_UI_PW_SELECT     191
#define IDD_LOCAL_DLG                   193
#define IDB_BACK_UI_01                  194
#define IDB_LOCAL_ITALIAN               210
#define IDB_LOCAL_ENGLISH               211
#define IDB_LOCAL_FRANCE                212
#define IDB_LOCAL_GERMANY               213
#define IDB_LOCAL_POLISH                214
#define IDB_LOCAL_TURKEY                215
#define IDB_BITMAP3                     216
#define IDB_BACK_LOCAL                  217
#define IDB_BITMAP5                     218
#define IDB_LOCAL_START                 219
#define IDB_BACK_LOCAL_SMALL            220
#define IDR_TXT_ERROR                   221
#define IDR_TXT_ERROR_EU                225
#define IDR_TXT_ERROR_ID                226
#define IDR_TXT_ERROR_NA                227
#define IDR_TXT_ERROR_SA                228
#define IDR_TXT_ERROR_TH                229
#define IDR_TXT6                        230
#define IDR_TXT_ERROR_TW                230
#define IDC_ERROR_EDIT                  1000
#define IDC_SETUP_FOLDER_BUTTON         1001
#define ID_SOLUTION                     1002
#define IDC_SETUP                       1004
#define IDC_EXIT                        1005
#define IDC_X                           1006
#define IDC_EDIT                        1007
#define ID_EXIT_BTN                     1008
#define ID_XBTN                         1009
#define IDC_LOGIN_X                     1010
#define IDC_EDIT_ID                     1011
#define IDC_EDIT_PW                     1012
#define IDC_ENTRY                       1014
#define IDC_FIND                        1015
#define IDC_LOGIN                       1017
#define IDC_IDSAVE                      1018
#define IDC_LOGIN_FIND_PW               1020
#define IDC_LIST1                       1021
#define IDC_CHANNEL                     1023
#define IDC_NAVER                       1024
#define IDC_MGAME                       1025
#define IDC_LOSTSAGA                    1026
#define IDC_NEXON                       1028
#define IDC_TOONI                       1029
#define IDC_DAUM                        1030
#define IDC_BUTTON1                     1031
#define IDC_BUTTON2                     1032
#define IDC_BUTTON4                     1034
#define IDC_BUTTON7                     1037

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        231
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
